---
title: "Why Data Science?"
author: "Laura Lazarescou"
date: "11/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Why Not Data Science?

I have mentored students and young professionals, and often I would encourage them to pursue
data science because it is still defining itself, there are thousands of jobs and there will 
be thousands more and those are all great things.

I love a good challenge and this MS in Data Science at SMU will bring me full circle, back to my 
early days of data modeling and app dev with an updated, relatively rare combination of skills.

I am passionate about giving back to the broader community, so developing these skills will
allow me to support non-profits and public sector organizations in ways that I could not have helped
otherwise.  

Who knows what is ahead of us?  In my opinion, data science is a topic that allows one to see
opportunities they would not be able to see until you jump in and give it a try!







